export const actionsEnums = {
	WEB3_CONNECTED: "WEB3_CONNECTED",
	SET_ACCOUNTS: "SET_ACCOUNTS",
	SET_NETWORK_ID: "SET_NETWORK_ID",
	SET_ERROR_TOAST: "SET_ERROR_TOAST",
	SET_INFO_TOAST: "SET_INFO_TOAST",
	SET_SUCCESS_TOAST: "SET_SUCCESS_TOAST",
	CLEAR_TOAST: "CLEAR_TOAST",
	DETECT_MOBILE_BROWSER: "DETECT_MOBILE_BROWSER"
};
